### ISSUE TITLE
Can´t execute diffusers 0.29.1 in Forge, also in A1111

### ISSUE THREAD

**Issue by cbresciano** [DenOfEquity/StableDiffusion3-for-webUI#1]
SD3 native support still does not work well with Auto1111 1.10.0RC. SD3 files are rejected at upload completion.
I tested the extension in Auto1111, placing diffusers>=0.29.1 in the version requirements file and in the boot of A1111, version 0.29.2 runs and the extension tab appears. Even so, when trying to generate an image an error appears. SD3 models are not downloaded online either.
With Forge, I replace the diffusers==0.25 line that is in the requirements file, with diffusers>=0.29.1 and even then, Forge continues loading version 0.25 and the extension tab does not appear. No model is downloaded online either. I use the token file in both cases as needed.

**Comment by DenOfEquity** [comment]
Models not downloading could be down to a couple of things:
1. Have you also accepted the terms at https://huggingface.co/stabilityai/stable-diffusion-3-medium-diffusers ?
2. Failure to read the access token or incorrect access token. If the token file doesn't load, there will be a message in the console: ```SD3: couldn't load 'huggingface_access_token.txt' from the webui directory. ... ``` Also, the token should be the only thing in that file, and it should be a plain text file. To clarify, this file will be in the same directory as ```requirements_versions.txt```.

Once you've edited the ```requirements_versions.txt```, Forge should update diffusers when you next start the server, same as A1111 did. I've done it like this several times, including on fresh installs, so I'm unsure why it's not working for you. You could check ```requirements.txt``` to make sure that doesn't set the version to 0.25, but the default Forge install doesn't do this. Without an updated diffusers version the extension will fail to load, so no tab will appear. There's probably a console message saying that an import failed. Models are downloaded on first generate, not on extension install or load.

edit: I've looked at the python file used when the webui (A1111 and Forge) starts: it checks/installs based on **requirements_versions.txt** and doesn't check **requirements.txt** at all.

**Comment by DenOfEquity** [comment]
Updated extension, after testing on an old A1111 install (now updated to 1.9.3). I had to update **tokenizers** and **transformers** and **huggingface-hub**.
There is now a console warning on startup in A1111 relating to the new version of huggingface-hub, but it doesn't seem important.
I then found that some components (tokenizers, text encoders) want the access token passed with a different keyword argument to that used by other components. And of course, they didn't complain about the unrecognized argument when loading locally. Fixed.

**Comment by cbresciano** [comment]
I have gone to the TOS page in Hugging Face and there is no link or button to accept the Terms. I guess it is done when creating the account. Also, when running Auto1111 v1.9.4 and 1.10RC, in both it loads diffusers 0.29.2 which is the latest version. The error appears when I want to generate an image and no model is downloaded. In the edit option "access token",  in repository permissions, I have put two repos: stabilityai/stable-diffusion-3-medium and stabilityai/stable-diffusion-3-medium-diffusers, to have access to repos. Also in requirements_version.txt I included the token value. I did something wrong?

    On Saturday, July 20, 2024 at 10:45:56 AM GMT-3, DenOfEquity ***@***.***> wrote:  
 
 


Updated extension, after testing on an old A1111 install (now updated to 1.9.3). I had to update tokenizers and transformers and huggingface-hub.
There is now a console warning on startup in A1111 relating to the new version of huggingface-hub, but it doesn't seem important.
I then found that some components (tokenizers, text encoders) want the access token passed with a different keyword argument to that used by other components. And of course, they didn't complain about the unrecognized argument when loading locally. Fixed.

**Comment by DenOfEquity** [comment]
The terms I referred to are for Stable Diffusion 3 - the model itself is gated behind usage terms. So, login to your huggingface account, go to the Stable Diffusion 3 medium diffusers repo (linked previously) and accept terms there. Once done, there will be a line near the top of the page saying ```Gated model
You have been granted access to this model```

You definitely have at least one problem with the access token; I recommend starting over:
1. Be logged in to huggingface.
2. go to https://huggingface.co/settings/tokens
3. click '+Create new token'
4. Set token type to 'Read', give it a name (doesn't matter what).
5. click 'Create token'
6. copy token, paste into a textfile called ```huggingface_access_token.txt``` in your webui directory. You'll have to create this textfile yourself. If you have file extensions hidden, then the visible file name should be just ```huggingface_access_token```.

```requirements_versions.txt``` is for the webui itself, so it knows what packages it needs. The access token is meaningless in there.

**Comment by cbresciano** [comment]
Thanks for the response and effort. I did the new modifications on Auto1111 1.10RC and now the image generation works. As for Forge, it still loads diffusers 0.25. It would be useful to read what the author says on https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/801. No problem with Forge since Stablitymatrix will include reForge, a project that takes Forge where he left off and is more active. As for Auto1111, what I see is that every time an image is generated, the console says "loading pipeline components" and the loading is extremely slow, I’m talking about many minutes, because the bottleneck of a generation is in memory load. Is there a way that you don’t have to reload pipelines every time an image is generated?

    On Sunday, July 21, 2024 at 10:08:56 PM GMT-3, DenOfEquity ***@***.***> wrote:  
 
 


The terms I referred to are for Stable Diffusion 3 - the model itself is gated behind usage terms. So, login to your huggingface account, go to the Stable Diffusion 3 medium diffusers repo (linked previously) and accept terms there. Once done, there will be a line near the top of the page saying Gated model You have been granted access to this model

You definitely have at least one problem with the access token; I recommend starting over:
   
   - Be logged in to huggingface.
   - go to https://huggingface.co/settings/tokens
   - click '+Create new token'
   - Set token type to 'Read', give it a name (doesn't matter what).
   - click 'Create token'
   - copy token, paste into a textfile called huggingface_access_token.txt in your webui directory. You'll have to create this textfile yourself. If you have file extensions hidden, then the visible file name should be just huggingface_access_token.

requirements_versions.txt is for the webui itself, so it knows what packages it needs. The access token is meaningless in there.

**Comment by DenOfEquity** [comment]
I'd kind of assumed most people have SSDs, so loading times would be negligible (it's a few seconds for me; then ~30s for T5 text encoder; then ~130s for inference at 1024x1024, 20 steps; then ~15+ seconds for VAE), and I thought it should play nicer with other applications to unload/free memory. But loading 14.4GB of models from HD every time the prompt is changed would be unfun. And making applications play nice is the job of the OS.
I'm currently testing a system where models are kept in VRAM/RAM memory. Seems like it could work better than I imagined, and doesn't even make the code much more complicated. Hopefully update later.

**Comment by DenOfEquity** [comment]
Added branch 'noUnload'. I suggest disabling the current extension before installing from that branch.

It keeps models in RAM or VRAM. Seems not possible to do this in an ideal way that still works on 8GB VRAM / 16GB RAM (hence not updating the main branch), so I'm getting inference speeds 25+% slower. But if model loading was taking multiple minutes, this is relatively minor.

**Comment by cbresciano** [comment]
The noUnload version is really fast!. Compared to the loading and unloading delay that was eternal. Which SD3 model is using the extension? I try to make a woman’s image and the skin is unreal. I would like to be able to test some checkpoints SD3 of Civitai. Do not know how to choose them from the extension and where it is stored in Auto1111 the model SD3 used. Would be an improvement to do? I updated Forge and had to rewrite the instructions for diffusers 0.29.1 and three others, it is a price to pay in each update. Thanks for your help
    On Monday, July 22, 2024 at 10:45:43 PM GMT-3, DenOfEquity ***@***.***> wrote:  
 
 


Added branch 'noUnload'. I suggest disabling the current extension before installing from that branch.

It keeps models in RAM or VRAM. Seems not possible to do this in an ideal way that still works on 8GB VRAM / 16GB RAM (hence not updating the main branch), so I'm getting inference speeds 25+% slower. But if model loading was taking multiple minutes, this is relatively minor.

**Comment by DenOfEquity** [comment]
Current version uses only the standard model.
I've been playing around with finetunes today. Next release will have support for custom transformers (the image generating part of the model). But my testing isn't showing much/any improvement over the base model. (One of the models I tested seems only to work at 768x768.)
For generating images of people, you'll get better results with sd1.5 or sdXL models. For this use case, I think that will be true for quite some time yet - maybe even until StabilityAI release v3.1 (if they do).
Anyway, I'm glad the noUnload branch is working better for you. I'll close this issue now, as it's left the original (resolved) topic.
